### ISSUE TITLE
登录页切换中英文无效

### ISSUE THREAD

**Issue by gujiwuqing** [H5-Dooring/dooringx#10]
![image](https://user-images.githubusercontent.com/44566835/131939428-4ef643c9-5269-487c-b125-0a10f4396419.png)
bug 如图所示 点击网站进去跳转登录页 登录页的切换中英文无效

**Comment by yehuozhili** [comment]
也不算bug吧 那个没来得及做

**Comment by gujiwuqing** [comment]
> 也不算bug吧 那个没来得及做

噗。。我还以为是写了有bug、、
