### ISSUE TITLE
只留了一个空架子

### ISSUE THREAD

**Issue by thk-liu** [H5-Dooring/dooringx#14]
这次版本采取lerna分包的方式设计挺合理的。
但是这次比之前的版本内容更是只是空架子和文档给出的宣传内容一点都不符合！

**Comment by yehuozhili** [comment]
本来就是免费提供基座给大家更快的开发类似应用，对于组件部分可以结合自身业务进行开发。dooringx是基于这个基座做的，并没有做完，组件部分普适性还在讨论中，后续有可能会提供一套普适性的基础组件。开发文档已经提供了，对于着急的同学可以拿这个直接做了。

**Comment by jiliangmason** [comment]
组件方面是只能支持react的组件吗？

**Comment by GeekQiaQia** [comment]
> 组件方面是只能支持react的组件吗？
目前来说，当前整个框架都是react生态搭建，最好使用react相关UI组件库，当然您可以尝试使用跨语言组件库，作为二次开发组件；
