### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by Popxie** [H5-Dooring/dooringx#2]
看了文档之后我得到的信息是：

> 这是一款可以 定制开发可视化拖拽平台

但是我依旧不明白他有啥作用？
我拖拽的目的是什么？
我拖拽完了以后有什么实质性的产出呢？
应用场景是什么啊？

综上就是：我用你这个开源的项目 我能得到什么产出（结果）。

![33.jpg](https://raw.githubusercontent.com/Popxie/kaka-img-repo/master/img/funny/33.jpg)

刚clone下来了 安装了依赖，各种报错，跑不起来··· 果断放弃了！[捂脸]

**Comment by yehuozhili** [comment]
你可能没有做过营销活动页，很多公司营销活动页需求紧急排期很短，用这个可以快速生成活动。因为lib只提供编辑器相关，所以后续怎么产出，各家有各家玩法。关于你报错，不是你node版本太低就是你没用yarn装。

**Comment by flyingbirdhub** [comment]
> 你可能没有做过营销活动页，很多公司营销活动页需求紧急排期很短，用这个可以快速生成活动。因为lib只提供编辑器相关，所以后续怎么产出，各家有各家玩法。关于你报错，不是你node版本太低就是你没用yarn装。

readme中可以给开发者提供一些开发指引😂

**Comment by wangbin980608** [comment]
> 你可能没有做过营销活动页，很多公司营销活动页需求紧急排期很短，用这个可以快速生成活动。因为lib只提供编辑器相关，所以后续怎么产出，各家有各家玩法。关于你报错，不是你node版本太低就是你没用yarn装。

![image](https://user-images.githubusercontent.com/53610901/127462832-4ab3cf6a-0902-4c73-9101-e19171a39069.png)
也没说一定要用yarn啊，我node版本是最新的装完依赖还是报错，少文件了还是咋地。注释这引用可以跑起来但是还是报错
![image](https://user-images.githubusercontent.com/53610901/127463019-2840ed69-80a1-4d3a-8fe0-919526a706b2.png)
![image](https://user-images.githubusercontent.com/53610901/127463199-5fbcf1bb-aff5-4aad-aef3-831e02526762.png)

**Comment by yehuozhili** [comment]
先build出lib再开example或者example安装lib

**Comment by wangbin980608** [comment]
> 先build出lib再开example或者example安装lib

文档太简单了，各种依赖安装不够明确啊

**Comment by yehuozhili** [comment]
这个库是拿来装的，只是example是这么用而已

**Comment by markexin** [comment]
可以正常启动，最好使用yarn
优先 yarn build  其次 yarn start:example
node: v16.0.0
postcss: 8

**Comment by Popxie** [comment]
> 你可能没有做过营销活动页，很多公司营销活动页需求紧急排期很短，用这个可以快速生成活动。因为lib只提供编辑器相关，所以后续怎么产出，各家有各家玩法。关于你报错，不是你node版本太低就是你没用yarn装。

**Comment by Popxie** [comment]
> 你可能没有做过营销活动页，很多公司营销活动页需求紧急排期很短，用这个可以快速生成活动。因为lib只提供编辑器相关，所以后续怎么产出，各家有各家玩法。关于你报错，不是你node版本太低就是你没用yarn装。

还好吧，不是很低。我是在这个仓库个根目录执行的安装依赖以及 yarn start，走到这里卡主了，各种报错。
```bash
$ yarn -v
1.22.4

$ node -v
v12.16.1
```

**Comment by Popxie** [comment]
> 你可能没有做过营销活动页，很多公司营销活动页需求紧急排期很短，用这个可以快速生成活动。因为lib只提供编辑器相关，所以后续怎么产出，各家有各家玩法。关于你报错，不是你node版本太低就是你没用yarn装。

这里所说的快速生成营销活动指的是 通过你的这个项目 可以生成xxx.html文件吗？

**Comment by yehuozhili** [comment]
简单理解生成xxx.html也对，实际上任何生成东西都是页面中已有的东西接收了json后在页面上按json规则进行排布处理。
