### ISSUE TITLE
基座的流畅度卡顿

### ISSUE THREAD

**Issue by ShallowGreen** [H5-Dooring/dooringx#22]
基座的拉伸流畅度和你们官方部署的流畅度有明显区别，可以更新一下基座的优化代码嘛

**Comment by yehuozhili** [comment]
你搞错了吧，是因为你在基座里打开控制台拖拽所以感觉流畅度不如dooringx的，其实dooringx上面的比基座要卡点

**Comment by ShallowGreen** [comment]
> 你搞错了吧，是因为你在基座里打开控制台拖拽所以感觉流畅度不如dooringx的，其实dooringx上面的比基座要卡点

确实，控制台的原因。
