### ISSUE TITLE
请教一下，有无办法调试dooringx-lib里面的代码？

### ISSUE THREAD

**Issue by Hujianboo** [H5-Dooring/dooringx#26]
从代码里学到了很多思路！有个开发问题想请教一下,
因为现在的monorepo结构，引用dooringx-lib都是构建后的产物，不能直接调试里面的源代码。
请问开发时是怎么调试的，是每次更改都重新build一下吗

**Comment by yehuozhili** [comment]
他不是有watch么，有sourcemap都能看见的。要么就是几个项目用一个打包器。

**Comment by Hujianboo** [comment]
> 

感谢回复！

**Comment by Hujianboo** [comment]
> 他不是有watch么，有sourcemap都能看见的。要么就是几个项目用一个打包器。

感谢！！
