### ISSUE TITLE
[问题]怎么修改左侧内容的样式？

### ISSUE THREAD

**Issue by BabyFriedCake** [H5-Dooring/dooringx#29]
怎么修改左侧里的样式？

**Comment by yehuozhili** [comment]
你这个是antd的css没加载上吧

**Comment by BabyFriedCake** [comment]
> 你这个是antd的css没加载上吧

我想重写里面的样式，能做到么？

**Comment by yehuozhili** [comment]
对着类名写 想要啥样式不是都有，另外这个组件有些配置项也能改变样式

**Comment by yehuozhili** [comment]
这个是cssmodule 后面都会带哈希值 你得找没带cssmodule的类名覆盖

**Comment by fangkyi03** [comment]
你现在知道为啥那些大型项目都不用css-module了吧 因为这个给自己用方便 但是给别人用不方便了
