### ISSUE TITLE
可否增加一个tab容器组件

### ISSUE THREAD

**Issue by toodiff** [H5-Dooring/dooringx#34]
1、一个组件拖拽时候会有卡顿
2、新需求，可否增加一个tab容器，tab标签页可动态增加，每个tab下面板是个容器，容器里可以拖拽左侧组件进去，点击tab标签可切换面板再拖拽组件，这种需求应该还是比较常见的

**Comment by yehuozhili** [comment]
正在考虑制作tab标签的问题，目前tab标签可以通过制作固定形式的tab标签页或者结合事件去制作，但是结合事件做起来不是特别方便，会有很多组件在同一位置，所以正在考虑使用新的方式去解决它

**Comment by yehuozhili** [comment]
组件拖拽的优化得下一个大版本做，到时候用另一种模式整个重写

**Comment by toodiff** [comment]
> 

这个有大概时间点吗

**Comment by toodiff** [comment]
> 正在考虑制作tab标签的问题，目前tab标签可以通过制作固定形式的tab标签页或者结合事件去制作，但是结合事件做起来不是特别方便，会有很多组件在同一位置，所以正在考虑使用新的方式去解决它

这个有大概时间点吗

**Comment by yehuozhili** [comment]
这个功能到时候改的可能比较多，数据格式也要变，估计在8月前搞完

**Comment by toodiff** [comment]
> 这个功能到时候改的可能比较多，数据格式也要变，估计在8月前搞完

好的
