### ISSUE TITLE
请问addRightCategory函数如何使用？如果想要异步新增或删除右侧tabs，只靠addRightCategory可以实现么？

### ISSUE THREAD

**Issue by chao-smile** [H5-Dooring/dooringx#35]
![image](https://user-images.githubusercontent.com/105209201/169747355-0b402a6c-0d8e-4f59-89db-2246dcb4d5d2.png)

**Comment by yehuozhili** [comment]
这个方法最早试可以的，后面没试过了，一般都是异步增加左侧，右侧的需求很少
