### ISSUE TITLE
怎么配置画布大小

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [H5-Dooring/dooringx#5]
现在画布的最小值被限定，不知道在那配置？

**Comment by yehuozhili** [comment]
画布设的最小值是为了后面做适配，为啥要改最小值呢？

**Comment by liuhuapiaoyuan** [comment]
如果制作横版的海报，而不是网页呢？

**Comment by yehuozhili** [comment]
横版正常也是把图像旋转放进去，不需要改最小值，后面到时候加个画布旋转，做起来方便点。

**Comment by yehuozhili** [comment]
你是要配那种高度很短的是吧，然后横屏之后会出现滚动条不太好，需要改最小值是吧。这个我后面再看看咋改比较好

**Comment by yehuozhili** [comment]
我修改了下  现在试试0.8.0版本，允许最小值到0，看看有没有什么问题

**Comment by liuhuapiaoyuan** [comment]
牛牛牛 更新很快，你们支持PR吗？

**Comment by yehuozhili** [comment]
支持啊

**Comment by 1134961980** [comment]
请问一下example打开之后这样正常吗？就全是空白，没有没有任何组件
![1628671122(1)](https://user-images.githubusercontent.com/66771066/128997855-bd4dc441-812b-43b1-a8d0-15d5b7800d24.jpg)
