### ISSUE TITLE
疑惑

### ISSUE THREAD

**Issue by 1134961980** [H5-Dooring/dooringx#6]
请问一下example打开之后这样正常吗？就全是空白，没有没有任何组件
![1628671122(1)](https://user-images.githubusercontent.com/66771066/128997855-bd4dc441-812b-43b1-a8d0-15d5b7800d24.jpg)

**Comment by yehuozhili** [comment]
正常 只是个demo 剩下的要看文档加。 截图是我们基于这个加的，还没做完

**Comment by 1134961980** [comment]
okok，收到，谢谢
